---
abstract: 'Simple minilanguage for use in expression'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Data::Clone: 0
  Data::Rmap: 0
  Module::Build: 0.3601
  Test::Exception: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Language-Expr
requires:
  List::MoreUtils: 0
  Moo: 0
  Moo::Role: 0
  Regexp::Grammars: 1.005
  UUID::Tiny: 0
  boolean: 0.20
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Language-Expr
  repository: http://github.com/sharyanto/perl-Language-Expr
version: 0.20
